---
title: "Data Cleaning and analysis"
subtitle: "Supplemental Materials: R Code Workflow"
author: "Chaopai Lin"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: True
      smooth_scroll: false
    code_download: true
    anchor_sections: true
    # df_print: kable
    highlight: pygments
editor_options: 
  markdown: 
    wrap: 72
---

```{=html}
<style type="text/css">
  body { font-family: "Source Sans Pro", Arial, sans-serif;
         font-size: 14px; color: #000;}
  #header { text-align: center; }
  h1, h2, h3 { font-weight: bold; }
  h1.title { font-size: 34px; }
  h1 { font-size: 32px; }
  h2 { font-size: 28px; }
  h3 { font-size: 24px; }
  h4 { font-size: 20px; }
  #TOC li { font-size: 18px; line-height: 1.25; }
  p, li, button span { font-size: 16px; }
  .table { table-layout: fixed; width: auto; margin: 1em auto; }
  .table thead { background-color: #f0f0f0; }
  .table tr.even { background-color: #f5f5f5; }
  .table { border-top: 1px solid #111; border-bottom: 1px solid #111; }
  .table thead tr th { border-bottom-width: 0px; line-height: 1.2; }
  .table tbody tr td { border-top-width: 0px; line-height: 1.2; }
  pre code { font-family: "Consolas", "Monaco", monospace;}
  pre code span.do { font-weight: bold; }
  pre code span.fu { color: #8959a8; }
</style>
```

```{r Config, include=FALSE}
options(
  knitr.kable.NA = "",
  digits = 3
)
knitr::opts_chunk$set(
  echo = FALSE,
  # collapse = TRUE,
  comment = "",
  fig.width = 8,
  fig.height = 6,
  dpi = 500
)
```

#  Analysis Flow
A flowchart should be displayed here.

# Setting
## Packages and Directory

```{r, echo = TRUE, results='hide', message=FALSE, warning=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
library(naniar)
library(table1)
library(psych)
library(MplusAutomation)
library(texreg)
library(bruceR)

set.wd()
```


## Functions
Hidden from the output

```{r}

```


# Data Preparation
## Import

```{r, echo=TRUE}

```


# Methods
## Demographic

```{r}

```

## Reliability

```{r}

```


# Results
## Primary Analysis

```{r}

```

## Correlation

```{r}

```

## Models
```{r}

```

