
#' Model fit table
#'
#' Use the information from \code{MplusAutomation} to create a model fit table
#' @param modelList Generated by readModels in MplusAutomation, can be a single object or a list
#' @param indices which indices be reported
#' @param ref Reference group in the model comparison, default is the latest model
#' @param diffTest Should the comparison included? Including change of CFI, TLI, and Chi-square.
#' @param digits the digits of each indice, degree of freedom is always the integer.
#'
#' @returns a \code{data.table} object
#' @export
#'
#' @examples
#'
#'fit_table(model2),
#'     keepCols = bruceR::cc("Title, Observations, ChiSqM_Value, ChiSqM_DF, CFI, TLI, RMSEA_Estimate, SRMR")) %>%
#'     mutate(Title = "Coefficients", digits = 3)
#'
#' fit_table(list(models$model1, models$model2, models$model2)),
#'     keepCols = bruceR::cc("Title, Observations, ChiSqM_Value, ChiSqM_DF, CFI, TLI, RMSEA_Estimate, SRMR")) %>%
#'     mutate(Title = bruceR::cccc("model1, model2, model3"), digits = 3)

fit_table <- function(modelList,
                      indices = c("Filename", "ChiSqM_Value", "ChiSqM_DF",
                                  "CFI", "TLI", "RMSEA_Estimate", "SRMR"),
                      ref = c("last", "first"),
                      diffTest = TRUE,
                      digits = 3) {
  ref <- match.arg(ref)

  # If a single model object is provided (i.e., it has a "summaries" element), wrap it in a list.
  if ("summaries" %in% names(modelList)) {
    modelList <- list(modelList)
  }

  # Validate that every model has a "summaries" element.
  for (i in seq_along(modelList)) {
    if (!("summaries" %in% names(modelList[[i]]))) {
      stop(sprintf("Model %d does not contain a 'summaries' element.", i))
    }
  }

  # Extract summaries (full data) for later calculations.
  summaries_list <- lapply(modelList, function(model) as.data.frame(model[["summaries"]]))

  # Combine summaries into one data frame.
  combined_table <- do.call(rbind, summaries_list)

  # Warn if some of the default indices are missing.
  missing_cols <- setdiff(indices, names(combined_table))
  if (length(missing_cols) > 0) {
    warning(sprintf("The following indices are missing from the model summaries: %s",
                    paste(missing_cols, collapse = ", ")))
  }

  # Convert key columns to numeric (if they exist).
  if ("CFI" %in% names(combined_table))
    combined_table$CFI <- as.numeric(as.character(combined_table$CFI))
  if ("TLI" %in% names(combined_table))
    combined_table$TLI <- as.numeric(as.character(combined_table$TLI))
  if ("RMSEA_Estimate" %in% names(combined_table))
    combined_table$RMSEA_Estimate <- as.numeric(as.character(combined_table$RMSEA_Estimate))
  if ("ChiSqM_Value" %in% names(combined_table))
    combined_table$ChiSqM_Value <- as.numeric(as.character(combined_table$ChiSqM_Value))
  if ("ChiSqM_DF" %in% names(combined_table))
    combined_table$ChiSqM_DF <- as.numeric(as.character(combined_table$ChiSqM_DF))
  if ("LL" %in% names(combined_table))
    combined_table$LL <- as.numeric(as.character(combined_table$LL))
  if ("Parameters" %in% names(combined_table))
    combined_table$Parameters <- as.numeric(as.character(combined_table$Parameters))

  n <- nrow(combined_table)

  # Initialize vectors for difference columns.
  diff_CFI   <- rep(NA, n)
  diff_TLI   <- rep(NA, n)
  diff_RMSEA <- rep(NA, n)
  chisq_diff <- rep("", n)   # concatenated chi-square difference details (diff, df, stars)
  chisq_p    <- rep("", n)   # separate p-value column

  # Decide whether to use alternative calculation (LL and Parameters) if ChiSqM_Value is unavailable.
  use_alternative <- FALSE
  if (!("ChiSqM_Value" %in% names(combined_table)) || all(is.na(combined_table$ChiSqM_Value))) {
    if (("LL" %in% names(combined_table)) && ("Parameters" %in% names(combined_table))) {
      use_alternative <- TRUE
      message("Notice: Chi-square differences computed based on log-likelihood and parameters.")
    }
  }

  # If diffTest is TRUE, compute the difference metrics.
  if (diffTest && n > 0) {
    for (i in 1:n) {
      # Determine the reference row based on the ref argument.
      if (ref == "first") {
        ref_row <- if (i == 1) NA else 1
      } else if (ref == "last") {
        ref_row <- if (i == 1) NA else i - 1
      }

      if (is.na(ref_row)) {
        diff_CFI[i]   <- NA
        diff_TLI[i]   <- NA
        diff_RMSEA[i] <- NA
        chisq_diff[i] <- ""
        chisq_p[i]    <- ""
      } else {
        # Compute differences for CFI, TLI, and RMSEA (current minus reference).
        if ("CFI" %in% names(combined_table))
          diff_CFI[i] <- combined_table$CFI[i] - combined_table$CFI[ref_row]
        if ("TLI" %in% names(combined_table))
          diff_TLI[i] <- combined_table$TLI[i] - combined_table$TLI[ref_row]
        if ("RMSEA_Estimate" %in% names(combined_table))
          diff_RMSEA[i] <- combined_table$RMSEA_Estimate[i] - combined_table$RMSEA_Estimate[ref_row]

        # Compute chi-square difference.
        if (!use_alternative && ("ChiSqM_Value" %in% names(combined_table)) &&
            ("ChiSqM_DF" %in% names(combined_table))) {
          delta_chisq <- combined_table$ChiSqM_Value[i] - combined_table$ChiSqM_Value[ref_row]
          delta_df    <- combined_table$ChiSqM_DF[i] - combined_table$ChiSqM_DF[ref_row]
        } else if (use_alternative && ("LL" %in% names(combined_table)) && ("Parameters" %in% names(combined_table))) {
          # Alternative chi-square calculation:
          # chi-square = -2 * (LL_ref - LL_current) with df = Parameters_current - Parameters_ref.
          delta_chisq <- -2 * (combined_table$LL[ref_row] - combined_table$LL[i])
          delta_df    <- combined_table$Parameters[i] - combined_table$Parameters[ref_row]
        } else {
          delta_chisq <- NA
          delta_df    <- NA
        }

        # Calculate the p-value for the chi-square difference test (if applicable).
        if (!is.na(delta_df) && delta_df > 0 && !is.na(delta_chisq)) {
          p_val <- 1 - pchisq(delta_chisq, df = delta_df)
        } else {
          p_val <- NA
        }

        # Determine significance stars based on the p-value.
        stars <- ""
        if (!is.na(p_val)) {
          if (p_val < 0.001) stars <- "***"
          else if (p_val < 0.01) stars <- "**"
          else if (p_val < 0.05) stars <- "*"
          else if (p_val < 0.1) stars <- "."
        }

        # Create the concatenated chi-square difference string.
        chisq_diff[i] <- if (!is.na(delta_chisq) && !is.na(delta_df))
          sprintf(paste0("%.", digits, "f (%d) %s"), delta_chisq, as.integer(delta_df), stars)
        else ""
        chisq_p[i] <- if (!is.na(p_val)) sprintf(paste0("%.", digits, "f"), p_val) else ""
      }
    }
  }

  # Create the final table by subsetting to the default indices.
  final_table <- combined_table[, intersect(indices, names(combined_table)), drop = FALSE]

  # If diffTest is TRUE, append the computed difference columns.
  if (diffTest) {
    final_table$diff_CFI   <- if ("CFI" %in% names(combined_table)) sprintf(paste0("%.", digits, "f"), diff_CFI) else NA
    final_table$diff_TLI   <- if ("TLI" %in% names(combined_table)) sprintf(paste0("%.", digits, "f"), diff_TLI) else NA
    final_table$diff_RMSEA <- if ("RMSEA_Estimate" %in% names(combined_table)) sprintf(paste0("%.", digits, "f"), diff_RMSEA) else NA
    final_table$chisq_diff <- chisq_diff
    final_table$chisq_p    <- chisq_p
  }

  # Format remaining numeric columns in the final table (except for ChiSqM_DF) to the specified digits.
  num_cols <- sapply(final_table, is.numeric)
  for (col in names(final_table)[num_cols]) {
    if (col != "ChiSqM_DF") {
      final_table[[col]] <- sprintf(paste0("%.", digits, "f"), final_table[[col]])
    }
  }

  # Remove row names to avoid overlap with the Filename column.
  rownames(final_table) <- NULL

  return(final_table)
}
