#' Create a Model Fit Table from MplusAutomation Output
#'
#' This function extracts summary statistics from one or more Mplus models generated by
#' the \code{MplusAutomation} package and creates a table of fit indices. It supports both
#' single model objects and lists of models. In the case of mixed input, the function flattens the inputs
#' so that each model's summary is processed.
#'
#' For model comparison, the function computes chi-square differences using:
#' \itemize{
#'   \item For \code{"ML"} models: a simple difference in chi-square values and degrees of freedom.
#'   \item For \code{"MLR"}, \code{"MLM"}, or \code{"WLSM"} models: a log-likelihood based chi-square
#'         difference test with a scaling correction factor.
#' }
#'
#' In addition, a new fit index, \code{"chisq/df"}, is calculated as the chi-square value divided by its
#' degrees of freedom. The default fit indices reported are \code{Models}, \code{Chisq}, \code{df}, \code{chisq/df},
#' \code{CFI}, \code{TLI}, \code{RMSEA}, and \code{SRMR}. Any additional indices provided via the
#' \code{indices} argument (e.g., \code{AIC} or \code{BIC}) are included alongside the defaults.
#'
#' When \code{diffTest} is \code{TRUE}, the function also computes change metrics for select fit indices.
#' The difference metrics are reported in the following order:
#' \enumerate{
#'   \item Chi-square difference and its p-value: \code{ΔChisq} and \code{p_ΔChisq}.
#'   \item Changes in CFI and RMSEA: \code{ΔCFI} and \code{ΔRMSEA}.
#'   \item Changes in AIC and BIC: \code{ΔAIC} and \code{ΔBIC} (computed only if \code{AIC} and \code{BIC} are specified in the \code{indices} argument).
#' }
#'
#' The final table columns are ordered with the default indices first (i.e.,
#' \code{c("Models", "Chisq", "df", "chisq/df", "CFI", "TLI", "RMSEA", "SRMR")}), followed by any available
#' LL, AIC, and BIC values, and finally the difference metrics in the order described above.
#'
#' @param ... One or more model objects or lists of models generated by \code{readModels} in MplusAutomation.
#' @param indices A character vector of additional indices to be reported. The default fit indices always include
#'   \code{Chisq}, \code{df}, \code{chisq/df}, \code{CFI}, \code{TLI}, \code{RMSEA}, and \code{SRMR}. To include
#'   difference metrics for \code{AIC} and \code{BIC}, include these in the vector.
#' @param ref Character string indicating the reference model for comparison. Either
#'   \code{"last"} (default; compare to the previous model) or \code{"first"}.
#' @param diffTest Logical. If \code{TRUE} (default), the function includes difference metrics
#'   (changes in CFI, RMSEA, AIC, BIC, and chi-square difference).
#' @param digits Integer specifying the number of digits for reporting the indices (except for df, which is always an integer).
#'
#' @return A \code{data.table} (data.frame) with the selected fit indices and, if requested,
#'   the computed difference metrics.
#'
#' @examples
#' \dontrun{
#'   # Example with a single model object:
#'   fit_table(models$model1)
#'
#'   # Example with a list of models:
#'   fit_table(list(models$model1, models$model2))
#'
#'   # Example with additional indices and difference metrics for AIC and BIC:
#'   fit_table(models$model1, indices = c("AIC", "BIC"))
#' }
#'
#' @export
fit_table <- function(...,
                      indices = character(0),  # Additional indices; defaults to none extra.
                      ref = c("last", "first"),
                      diffTest = TRUE,
                      digits = 3) {
  ref <- match.arg(ref)

  # Flatten input: if an argument is a list of models (without a "summaries" element),
  # then extract each model and add it to the main list.
  args <- list(...)
  modelList <- list()
  for (obj in args) {
    if (is.list(obj) && !("summaries" %in% names(obj))) {
      for (m in obj) {
        if (!("summaries" %in% names(m))) {
          stop("One of the models in a provided list does not contain a 'summaries' element.")
        }
        modelList[[length(modelList) + 1]] <- m
      }
    } else if (is.list(obj) && ("summaries" %in% names(obj))) {
      modelList[[length(modelList) + 1]] <- obj
    } else {
      stop("Input is not a valid model object or list of models.")
    }
  }

  # Validate that every model has a "summaries" element.
  for (i in seq_along(modelList)) {
    if (!("summaries" %in% names(modelList[[i]]))) {
      stop(sprintf("Model %d does not contain a 'summaries' element.", i))
    }
  }

  # Extract the summaries from each model.
  summaries_list <- lapply(modelList, function(model) as.data.frame(model[["summaries"]]))

  # Combine summaries into one data frame.
  combined_table <- do.call(rbind, summaries_list)

  # Calculate new index: chisq/df (handling division by zero).
  if (all(c("ChiSqM_Value", "ChiSqM_DF") %in% names(combined_table))) {
    combined_table[,"chisq/df"] <- with(combined_table, ifelse(ChiSqM_DF != 0, ChiSqM_Value / ChiSqM_DF, NA))
  } else {
    combined_table[,"chisq/df"] <- NA
  }

  # Define default indices that are always reported.
  default_indices <- c("Filename", "ChiSqM_Value", "ChiSqM_DF", "chisq/df", "CFI", "TLI", "RMSEA_Estimate", "SRMR")
  missing_defaults <- setdiff(default_indices, names(combined_table))
  if (length(missing_defaults) > 0) {
    warning(sprintf("The following default indices are missing from the model summaries: %s",
                    paste(missing_defaults, collapse = ", ")))
  }

  # Convert key columns to numeric.
  numeric_cols <- c("CFI", "TLI", "RMSEA_Estimate", "ChiSqM_Value", "ChiSqM_DF", "LL", "Parameters", "AIC", "BIC")
  for (col in numeric_cols) {
    if (col %in% names(combined_table))
      combined_table[[col]] <- as.numeric(as.character(combined_table[[col]]))
  }

  n <- nrow(combined_table)

  # Combine default indices with any additional ones provided.
  final_indices <- c(default_indices, setdiff(indices, default_indices))
  requested_indices <- intersect(final_indices, names(combined_table))
  final_table <- combined_table[, requested_indices, drop = FALSE]

  # Compute difference metrics if requested.
  if (diffTest && n > 0) {
    diff_CFI   <- rep(NA, n)
    diff_RMSEA <- rep(NA, n)
    diff_AIC   <- rep(NA, n)
    diff_BIC   <- rep(NA, n)
    diff_chisq <- rep("", n)    # For chi-square difference (value, df, significance stars)
    diff_chisq_p <- rep("", n)  # For chi-square difference p-value

    for (i in 1:n) {
      # Determine reference row.
      ref_row <- if (ref == "first") { if (i == 1) NA else 1 } else { if (i == 1) NA else i - 1 }

      if (is.na(ref_row)) {
        diff_CFI[i]   <- NA
        diff_RMSEA[i] <- NA
        diff_AIC[i]   <- NA
        diff_BIC[i]   <- NA
        diff_chisq[i] <- ""
        diff_chisq_p[i] <- ""
      } else {
        if ("CFI" %in% names(combined_table))
          diff_CFI[i] <- combined_table$CFI[i] - combined_table$CFI[ref_row]
        if ("RMSEA_Estimate" %in% names(combined_table))
          diff_RMSEA[i] <- combined_table$RMSEA_Estimate[i] - combined_table$RMSEA_Estimate[ref_row]
        if ("AIC" %in% names(combined_table))
          diff_AIC[i] <- combined_table$AIC[i] - combined_table$AIC[ref_row]
        if ("BIC" %in% names(combined_table))
          diff_BIC[i] <- combined_table$BIC[i] - combined_table$BIC[ref_row]

        # Compute chi-square difference.
        if (!is.na(combined_table$Estimator[i]) && !is.na(combined_table$Estimator[ref_row]) &&
            combined_table$Estimator[i] == combined_table$Estimator[ref_row]) {
          est <- combined_table$Estimator[i]
          if (est == "ML") {
            delta_chisq <- combined_table$ChiSqM_Value[i] - combined_table$ChiSqM_Value[ref_row]
            delta_df    <- combined_table$ChiSqM_DF[i] - combined_table$ChiSqM_DF[ref_row]
          } else if (est %in% c("MLR", "MLM", "WLSM")) {
            if (all(c("LL", "LLCorrectionFactor", "Parameters") %in% names(combined_table))) {
              if (combined_table$Parameters[i] > combined_table$Parameters[ref_row]) {
                H0_index <- ref_row
                H1_index <- i
              } else {
                H0_index <- i
                H1_index <- ref_row
              }
              cd <- (combined_table$Parameters[H0_index] * combined_table$LLCorrectionFactor[H0_index] -
                       combined_table$Parameters[H1_index] * combined_table$LLCorrectionFactor[H1_index]) /
                (combined_table$Parameters[H0_index] - combined_table$Parameters[H1_index])
              delta_chisq <- -2 * (combined_table$LL[H0_index] - combined_table$LL[H1_index]) / cd
              delta_df <- combined_table$Parameters[H1_index] - combined_table$Parameters[H0_index]
            } else {
              delta_chisq <- NA
              delta_df <- NA
            }
          } else {
            delta_chisq <- NA
            delta_df <- NA
          }
          p_val <- if (!is.na(delta_df) && delta_df > 0) 1 - pchisq(delta_chisq, df = delta_df) else NA
        } else {
          delta_chisq <- NA
          delta_df <- NA
          p_val <- NA
        }

        stars <- ""
        if (!is.na(p_val)) {
          if (p_val < 0.001) stars <- "***"
          else if (p_val < 0.01) stars <- "**"
          else if (p_val < 0.05) stars <- "*"
          else if (p_val < 0.1) stars <- "."
        }

        diff_chisq[i] <- if (!is.na(delta_chisq) && !is.na(delta_df))
          sprintf(paste0("%.", digits, "f (%d) %s"), delta_chisq, as.integer(delta_df), stars)
        else ""
        diff_chisq_p[i] <- if (!is.na(p_val)) sprintf(paste0("%.", digits, "f"), p_val) else ""
      }
    }
  }

  # Rename default columns for clarity.
  if ("Filename" %in% names(final_table))
    colnames(final_table)[colnames(final_table) == "Filename"] <- "Models"
  if ("ChiSqM_Value" %in% names(final_table))
    colnames(final_table)[colnames(final_table) == "ChiSqM_Value"] <- "Chisq"
  if ("ChiSqM_DF" %in% names(final_table))
    colnames(final_table)[colnames(final_table) == "ChiSqM_DF"] <- "df"
  if ("RMSEA_Estimate" %in% names(final_table))
    colnames(final_table)[colnames(final_table) == "RMSEA_Estimate"] <- "RMSEA"

  # Format numeric columns (except for df) to the specified number of digits.
  num_cols <- sapply(final_table, is.numeric)
  for (col in names(final_table)[num_cols]) {
    if (col != "df") {
      final_table[[col]] <- sprintf(paste0("%.", digits, "f"), final_table[[col]])
    }
  }

  # Append difference metrics if diffTest is TRUE, using a delta prefix.
  # Note: ΔAIC and ΔBIC are added only if "AIC" and "BIC" are included in the indices argument.
  if (diffTest) {
    final_table[,"ΔCFI"]   <- if ("CFI" %in% names(combined_table)) sprintf(paste0("%.", digits, "f"), diff_CFI) else NA
    final_table[,"ΔRMSEA"] <- if ("RMSEA_Estimate" %in% names(combined_table)) sprintf(paste0("%.", digits, "f"), diff_RMSEA) else NA
    final_table[,"ΔChisq"] <- diff_chisq
    final_table[,"p_ΔChisq"] <- diff_chisq_p
    if ("AIC" %in% indices && "AIC" %in% names(combined_table)) {
      final_table[,"ΔAIC"] <- sprintf(paste0("%.", digits, "f"), diff_AIC)
    }
    if ("BIC" %in% indices && "BIC" %in% names(combined_table)) {
      final_table[,"ΔBIC"] <- sprintf(paste0("%.", digits, "f"), diff_BIC)
    }
  }

  # Reorder the columns.
  # Group 1: Default indices in fixed order.
  default_order <- c("Models", "Chisq", "df", "chisq/df", "CFI", "TLI", "RMSEA", "SRMR")
  group1 <- intersect(default_order, colnames(final_table))

  # Group 2: LL, AIC, BIC block.
  group2 <- intersect(c("LL", "AIC", "BIC"), colnames(final_table))

  # Group 3: Difference metrics in specified order:
  # first chi-square difference (and its p-value), then ΔCFI and ΔRMSEA,
  # and then ΔAIC and ΔBIC (if available).
  group3 <- c("ΔChisq", "p_ΔChisq", "ΔCFI", "ΔRMSEA")
  if ("AIC" %in% indices && "ΔAIC" %in% colnames(final_table)) {
    group3 <- c(group3, "ΔAIC")
  }
  if ("BIC" %in% indices && "ΔBIC" %in% colnames(final_table)) {
    group3 <- c(group3, "ΔBIC")
  }

  # Append any remaining columns that are not in the above groups.
  remaining <- setdiff(colnames(final_table), c(group1, group2, group3))

  final_table <- final_table[, c(group1, group2, group3, remaining), drop = FALSE]

  rownames(final_table) <- NULL
  return(final_table)
}
