#' Interaction Plot
#'
#' Create an interaction plot based on estimated marginal means extracted from
#' a \code{\link[bruceR]{MANOVA}} result object. This function wraps
#' \code{\link[emmeans]{emmip}} with additional control over factor level
#' ordering for the x-axis, grouping variable, and faceting variable(s).
#'
#' @param result An object returned by \code{\link[bruceR]{MANOVA}}.
#'   Must be of class \code{afex_aov}.
#' @param formula A formula passed to \code{\link[emmeans]{emmip}}.
#'   The left-hand side specifies the grouping (trace) variable and the
#'   right-hand side specifies the x-axis variable. An optional conditioning
#'   variable can be added after \code{|} for faceting
#'   (e.g., \code{group ~ time | grade}).
#'   When the left-hand side is empty (e.g., \code{~ time}), a single line
#'   without grouping is plotted.
#' @param x_levels Optional character vector. Specifies the desired order of
#'   factor levels on the x-axis. If \code{NULL} (default), the original order
#'   from \code{emmip} is used.
#' @param group_levels Optional character vector. Specifies the desired order of
#'   factor levels for the grouping (trace) variable. If \code{NULL} (default),
#'   the original order from \code{emmip} is used.
#' @param facet_levels Optional named list of character vectors. Each element
#'   specifies the desired order of factor levels for a faceting variable.
#'   Names must match the faceting variable names in the data. If \code{NULL}
#'   (default), the original order from \code{emmip} is used.
#' @param CIs Logical. Whether to display confidence interval error bars.
#'   Defaults to \code{TRUE}.
#'
#' @return A \code{\link[ggplot2]{ggplot}} object.
#'
#' @details
#' \code{\link[bruceR]{MANOVA}} internally converts within-subjects factor
#' levels using \code{as.factor()}, which sorts levels alphabetically. This
#' can result in undesirable ordering on the x-axis (e.g., "post" before
#' "pre"). The \code{x_levels} argument provides a straightforward way to
#' override this behaviour.
#'
#' When the formula includes a conditioning variable (e.g., \code{group ~ time
#' | grade}), the plot is automatically faceted. The \code{facet_levels}
#' argument controls the panel order.
#'
#' When no grouping variable is specified (formula of the form \code{~ x}),
#' the legend is automatically suppressed.
#'
#' @examples
#' \dontrun{
#' library(bruceR)
#' library(emmeans)
#' library(ggplot2)
#'
#' # 2 (group) x 2 (time) mixed design
#' res <- MANOVA(
#'   data = dat,
#'   dvs = c("pre_mi", "post_mi"),
#'   dvs.pattern = "(.*)_mi",
#'   between = "group",
#'   within = "time"
#' )
#' plot_emm(res, group ~ time, x_levels = c("pre", "post"))
#'
#' # 2 (group) x 2 (time) x 3 (grade) mixed design with faceting
#' plot_emm(
#'   res2,
#'   formula = group ~ time | grade,
#'   x_levels = c("pre", "post"),
#'   facet_levels = list(grade = c("k1", "k2", "k3"))
#' )
#' }
#'
#' @importFrom emmeans emmip
#' @importFrom ggplot2 ggplot aes geom_line geom_point geom_errorbar
#'   position_dodge labs theme_minimal facet_wrap theme element_blank guides
#' @importFrom dplyr mutate
#' @export
plot_emm <- function(result,
                     formula = group ~ time,
                     x_levels = NULL,
                     group_levels = NULL,
                     facet_levels = NULL,
                     CIs = TRUE) {

  if (!inherits(result, "afex_aov")) {
    stop(
      "`result` must be an object returned by bruceR::MANOVA() (class 'afex_aov').",
      call. = FALSE
    )
  }

  # Extract estimated marginal means as a data frame
  emm_data <- emmeans::emmip(result, formula, CIs = CIs, plotit = FALSE)

  # Reorder x-axis factor levels
  if (!is.null(x_levels)) {
    emm_data <- dplyr::mutate(emm_data, xvar = factor(xvar, levels = x_levels))
  }

  # Reorder grouping (trace) factor levels
  if (!is.null(group_levels)) {
    emm_data <- dplyr::mutate(emm_data, tvar = factor(tvar, levels = group_levels))
  }

  # Identify facet variables: columns other than those generated by emmip
  fixed_cols <- c("xvar", "yvar", "tvar", "LCL", "UCL", "SE")
  facet_vars <- setdiff(names(emm_data), fixed_cols)

  # Reorder facet variable levels
  if (!is.null(facet_levels) && length(facet_vars) > 0) {
    for (fv in names(facet_levels)) {
      if (fv %in% names(emm_data)) {
        emm_data[[fv]] <- factor(emm_data[[fv]], levels = facet_levels[[fv]])
      }
    }
  }

  # Build the base plot
  p <- ggplot2::ggplot(emm_data, ggplot2::aes(x = xvar, y = yvar, group = tvar)) +
    ggplot2::geom_line(
      ggplot2::aes(linetype = tvar),
      linewidth = 0.6,
      position = ggplot2::position_dodge(width = 0.15)
    ) +
    ggplot2::geom_point(
      ggplot2::aes(shape = tvar),
      size = 2.5,
      position = ggplot2::position_dodge(width = 0.15)
    ) +
    ggplot2::labs(
      x = NULL,
      y = "Estimated Marginal Mean",
      linetype = NULL,
      shape = NULL
    ) +
    ggplot2::theme_minimal()

  # Add confidence interval error bars
  if (CIs) {
    p <- p +
      ggplot2::geom_errorbar(
        ggplot2::aes(ymin = LCL, ymax = UCL),
        width = 0.08,
        linewidth = 0.4,
        position = ggplot2::position_dodge(width = 0.15)
      )
  }

  # Add faceting if conditioning variables are present
  if (length(facet_vars) > 0) {
    p <- p + ggplot2::facet_wrap(facet_vars)
  }

  # Hide legend when there is no meaningful grouping variable
  if (length(unique(emm_data$tvar)) <= 1) {
    p <- p +
      ggplot2::guides(linetype = "none", shape = "none")
  }

  p
}
